version: '3.8'

services:
  webrtc-client-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_SIGNALING_URL: ${REACT_APP_SIGNALING_URL:-}
        REACT_APP_TURN_URLS: ${REACT_APP_TURN_URLS:-}
        REACT_APP_TURN_USERNAME: ${REACT_APP_TURN_USERNAME:-}
        REACT_APP_TURN_CREDENTIAL: ${REACT_APP_TURN_CREDENTIAL:-}
    image: saeedghofrani/webrtc-client:latest
    container_name: webrtc-client
    ports:
      - "127.0.0.1:25254:25254"
    restart: unless-stopped
    networks:
      - webnet

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:25254"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  webnet:
    driver: bridge
